---
output:
  pdf_document:
    template: cover-letter.template
    latex_engine: xelatex
    md_extensions: "-autolink_bare_uris"
author: Garrick Aden-Buie
opening: Dear Hiring Team,
closing: Sincerely,
date: '`r strftime(Sys.time(), "%B %e, %Y")`'
address:
- RStudio, PBC
- Boston, MA
return-address: |
  **Garrick Aden-Buie** \
  474 34th Ave N \
  St. Petersburg, FL \
cc:
encl:
ps:
# fontfamily: mathpazo
mainfont: Source Sans Pro
fontsize: 11pt
geometry: top=0.5in,left=1in,right=1in,bottom=1in
blockquote: true
# letterhead: example/letterhead.pdf
signature: gab-signature.pdf
signature-before: -8ex
signature-after: 0ex
closing-indentation: 0pt
links-as-notes: false
colorlinks: true
urlcolor: "bostonuniversityred"

basics:
  name: Garrick Aden-Buie
  website: https://www.garrickadenbuie.com
  phone: "(727) 344-9568"
  email: garrick@adenbuie.com
  location:
    address: 474 34th Ave N.
    postalCode: FL 33704
    city: St. Petersburg
    countryCode: US
    region: Florida
  other: []
  summary: Motivated, life-long learner. Always looking for questions and answers
    in the data. Passionate about collaboration, communicating insights, and sharing
    knowledge. Known as a highly organized, perceptive, and resourceful team player.
  profiles:
  - network: Github
    username: gadenbuie
    url: https://github.com/gadenbuie
  - network: Twitter
    username: grrrck
    url: https://twitter.com/grrrck
...

**R Markdown** is an indispensable part of my life.
I know it sounds hyperbolic to say.
But R Markdown is such a powerful tool for creating and sharing knowledge, that I think it's worth risking sounding cheesy.
But behind this statement is a deep respect for the technical choices that led to `rmarkdown`; respect for the low-level and conscious design choices that make it a versatile and approachable format for mixing prose and code.

I believe in R Markdown so much that the first task I undertook when designing the _JavaScript for Shiny Users_ workshop for rstudio::conf 2020 was to develop a custom JavaScript `knitr` engine that replicates the literate programming experience R users are accustomed to.
_How can anyone learn to program in a new language without R Markdown?_, I thought.

For years and to anyone who will listen, I have been happy to expound on the many benefits of R Markdown:
_The code that creates the plot, and the table, and the calculated statistic are woven together with the narrative within the same document!_
It has been an immense pleasure to watch the community embrace the format, to hear of university courses where `.Rmd` is the expected file extensions for assignments, to have conversations move from "What is it?" to "How do I...?".

As R Markdown has gained in popularity and acceptance, I have tried to give back to the community when and where I can, by sharing the things I've learned on my personal blog, by answering questions on Twitter or other sites, and by contributing pull requests whenever possible.
I have always found myself most interested and effortlessly enthusiastic when working on the tools and educational resources that empower data scientists and R users.

For these reasons, I believe I am uniquely qualified for the role of R Markdown Engineer.
This role will require technical proficiency with the R source code and development infrastructure of the `rmarkdown`-related packages; it will require an empathetic and perceptive educator who can triage and respond to issues reported by users of various technical skill levels; it will require a self-directed and motivated learner who can effectively manage their time.
On each of these key traits, my experience as an R developer, educator and life-long learner support my success in the role.

I look forward to discussing the role and my experience with you.